kind: Service
apiVersion: v1
metadata:
  name: ebpf-exporter-service
spec:
  selector:
    run: ebpf-exporter
  ports:
  - name: ebpf-metrics
    nodePort: 30900
    protocol: TCP
    port: 9435
    targetPort: 9435
  type: NodePort
