# Override default values here
##

grafana:
  adminUser: pjds
  adminPassword: pjds
  sidecar:
    dashboards:
      provider:
        allowUiUpdates: true

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'airflow'
        scrape_interval: 15s
        static_configs:
          - targets: ['airflow-statsd.airflow.svc.cluster.local:9102']
      - job_name: 'ebpf'
        scrape_interval: 5s
        kubernetes_sd_configs:
        - role: endpoints

kube-state-metrics:
  metricLabelsAllowlist:
    - namespaces=[*]
    - pods=[*]
  metricAnnotationsAllowList:
    - pods=[*]
    - namespaces=[*]
