{
 "title": "eBPF Disk I/O",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ebpf_exporter_bio_size_bytes_sum, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "biolatency read",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"$instance\", operation=\"read\"}[$__interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "biolatency write",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"$instance\", operation=\"write\"}[$__interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentiles and averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"$instance\"}[$__interval]) )",
     "legendFormat": "90% {{ operation }} ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"$instance\"}[$__interval]) )",
     "legendFormat": "95% {{ operation }} ({{instance}})"
    },
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_sum{instance=~\"$instance\"}[$__interval]) / rate(ebpf_exporter_bio_latency_seconds_count{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{ operation }} average ({{instance}})"
    }
   ]
  },
  { "title": "IO Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "bio bytes read",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_bucket{instance=~\"$instance\", operation=\"read\"}[$__interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "bio bytes write",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_bucket{instance=~\"$instance\", operation=\"write\"}[$__interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentiles and averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_bio_size_bytes_bucket{instance=~\"$instance\"}[$__interval]) )",
     "legendFormat": "90% {{ operation }} {{instance}})"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_bio_size_bytes_bucket{instance=~\"$instance\"}[$__interval]) )",
     "legendFormat": "95% {{ operation }} ({{instance}})"
    },
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_sum{instance=~\"$instance\"}[$__interval]) / rate(ebpf_exporter_bio_size_bytes_count{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{ operation }} average ({{instance}})"
    }
   ]
  },
  {
   "title": "Total bytes read/written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_sum{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Sum {{ operation }} ({{instance}})"
    }
   ]
  }
 ]
}