{
 "title": "eBPF biolatency",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ebpf_exporter_bio_size_bytes_sum, instance)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(ebpf_exporter_bio_size_bytes_sum, device)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ebpf_exporter_bio_size_bytes_sum, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# biolatency\nbiolatency traces block device I/O (disk I/O), and records the distribution\nof I/O latency"
   }
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "biolatency read",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"$instance\", device=~\"$device\", job=~\"$job\", operation=\"read\"}[$__interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "biolatency write",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"$instance\", device=~\"$device\", job=~\"$job\", operation=\"write\"}[$__interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentiles and averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"$instance\", device=~\"$device\", job=~\"$job\"}[$__interval]) )",
     "legendFormat": "90% {{ operation }} ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_bio_latency_seconds_bucket{instance=~\"$instance\", device=~\"$device\", job=~\"$job\"}[$__interval]) )",
     "legendFormat": "95% {{ operation }} ({{instance}})"
    },
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_sum{instance=~\"$instance\"}[$__interval]) / rate(ebpf_exporter_bio_latency_seconds_count{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{ operation }} average ({{instance}})"
    }
   ]
  },
  { "title": "IO Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "bio bytes read",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_bucket{instance=~\"$instance\", device=~\"$device\", job=~\"$job\", operation=\"read\"}[$__interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "bio bytes write",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_bucket{instance=~\"$instance\", operation=\"write\"}[$__interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentiles and averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_bio_size_bytes_bucket{instance=~\"$instance\"}[$__interval]) )",
     "legendFormat": "90% {{ operation }} {{instance}})"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_bio_size_bytes_bucket{instance=~\"$instance\"}[$__interval]) )",
     "legendFormat": "95% {{ operation }} ({{instance}})"
    },
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_sum{instance=~\"$instance\"}[$__interval]) / rate(ebpf_exporter_bio_size_bytes_count{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{ operation }} average ({{instance}})"
    }
   ]
  },
  {
   "title": "Total bytes read/written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_sum{instance=~\"$instance\", device=~\"$device\", job=~\"$job\"}[$__interval])",
     "legendFormat": "Sum {{ operation }} ({{instance}})"
    }
   ]
  }
 ]
}