{
 "title": "eBPF dcache",
 "description": "Show directroy entry cache (dcache) metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ebpf_exporter_dcache_ops_total, instance)"
    }
   },
   {
    "name": "command",
    "label": "Command",
    "query": {
     "query": "label_values(ebpf_exporter_dcache_ops_total, command)"
    }
   },
   {
    "name": "op",
    "label": "Operation",
    "query": {
     "query": "label_values(ebpf_exporter_dcache_ops_total, op)"
    }
   },
   {
    "name": "dag_id",
    "label": "DAG Id",
    "query": {
     "query": "label_values(ebpf_exporter_dcache_ops_total, dag_id)"
    }
   },
   {
    "name": "run_id",
    "label": "Run Id",
    "query": {
     "query": "label_values(ebpf_exporter_dcache_ops_total, run_id)"
    }
   },
   {
    "name": "task_id",
    "label": "Task Id",
    "query": {
     "query": "label_values(ebpf_exporter_dcache_ops_total, task_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# dcache\nThe  Linux  directory  entry cache (dcache) improves the performance of file and directory name lookups"
   }
  },
  {
   "title": "dcache Reference Rate",
   "type": "timeseries",
   "description": "The total references per second",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_dcache_ops_total{instance=~\"$instance\", command=~\"$command\", op=\"refs\"}[$__interval])",
     "legendFormat": "{{command}} ({{instance}})"
    }
   ]
  },
  {
   "title": "dcache Slow Rate",
   "type": "timeseries",
   "description": "The number that took a slower code path to be processed",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_dcache_ops_total{instance=~\"$instance\", command=~\"$command\", op=\"slow\"}[$__interval])",
     "legendFormat": "{{command}} ({{instance}})"
    }
   ]
  },
  {
   "title": "dcache Miss Rate",
   "type": "timeseries",
   "description": "The number of dcache misses",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_dcache_ops_total{instance=~\"$instance\", command=~\"$command\", op=\"miss\"}[$__interval])",
     "legendFormat": "{{command}} ({{instance}})"
    }
   ]
  }
 ]
}