{
 "title": "eBPF Syscalls",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "function",
    "label": "Function",
    "query": {
     "query": "label_values(ebpf_exporter_syscall_latency_seconds_sum, function)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ebpf_exporter_syscall_latency_seconds_sum, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# syscalls\nRecord latency of syscalls, including the entrypoint (do_syscall_64) and audit logging (syscall_slow_exit_work)"
   }
  },
  {
   "title": "Syscall Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_syscall_latency_seconds_bucket{instance=~\"$instance\", function=~\"$function\"}[$__interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_syscall_latency_seconds_bucket{instance=~\"$instance\", function=~\"$function\"}[$__interval]) )",
     "legendFormat": "90% {{function}} ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_syscall_latency_seconds_bucket{instance=~\"$instance\", function=~\"$function\"}[$__interval]) )",
     "legendFormat": "95% {{function}} ({{instance}})"
    },
    {
     "expr": "rate(ebpf_exporter_syscall_latency_seconds_sum{instance=~\"$instance\", function=~\"$function\"}[$__interval]) / rate(ebpf_exporter_syscall_latency_seconds_count{instance=~\"$instance\", function=~\"$function\"}[$__interval])",
     "legendFormat": "{{function}} average ({{instance}})"
    }
   ]
  },
  {
   "title": "Total Syscall Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_syscall_latency_seconds_sum{instance=~\"$instance\", function=~\"$function\"}[$__interval])",
     "legendFormat": "{{function}} ({{instance}})"
    }
   ]
  }
 ]
}