{
 "title": "eBPF Page Cache",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ebpf_exporter_page_cache_ops_total, instance)"
    }
   },
   {
    "name": "command",
    "label": "Command",
    "query": {
     "query": "label_values(ebpf_exporter_page_cache_ops_total, command)"
    }
   },
   {
    "name": "dag_id",
    "label": "DAG Id",
    "query": {
     "query": "label_values(ebpf_exporter_page_cache_ops_total, dag_id)"
    }
   },
   {
    "name": "run_id",
    "label": "Run Id",
    "query": {
     "query": "label_values(ebpf_exporter_page_cache_ops_total, run_id)"
    }
   },
   {
    "name": "task_id",
    "label": "Task Id",
    "query": {
     "query": "label_values(ebpf_exporter_page_cache_ops_total, task_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# cachestat\n\nMeasures cache activity"
   }
  },
  {
   "title": "Access",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_page_cache_ops_total{command=~\"$command\", op=~\"mark_page_accessed\", dag_id=~\"$dag_id\", run_id=~\"$run_id\", task_id=~\"$task_id\"}[$__interval])",
     "legendFormat": "{{command}} ({{instance}}) {{dag_id}}_{{run_id}}_{{task_id}}"
    }
   ]
  },
  {
   "title": "Insertions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_page_cache_ops_total{command=~\"$command\", op=~\"add_to_page_cache_lru\", dag_id=~\"$dag_id\", run_id=~\"$run_id\", task_id=~\"$task_id\"}[$__interval])",
     "legendFormat": "{{command}} ({{instance}}) {{dag_id}}_{{run_id}}_{{task_id}}"
    }
   ]
  },
  {
   "title": "Writes for Access",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_page_cache_ops_total{command=~\"$command\", op=~\"mark_buffer_dirty\", dag_id=~\"$dag_id\", run_id=~\"$run_id\", task_id=~\"$task_id\"}[$__interval])",
     "legendFormat": "{{command}} ({{instance}}) {{dag_id}}_{{run_id}}_{{task_id}}"
    }
   ]
  },
  {
   "title": "Writes for Insertions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_page_cache_ops_total{command=~\"$command\", op=~\"account_page_dirtied\", dag_id=~\"$dag_id\", run_id=~\"$run_id\", task_id=~\"$task_id\"}[$__interval])",
     "legendFormat": "{{command}} ({{instance}}) {{dag_id}}_{{run_id}}_{{task_id}}"
    }
   ]
  }
 ]
}