apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ebpf-exporter-swms.fullname" . }}
  labels:
    {{- include "ebpf-exporter-swms.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    matchLabels:
      {{- include "ebpf-exporter-swms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ebpf-exporter-swms.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ebpf-exporter-swms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9435
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config 
              mountPath: /config/
            - name: kernel
              mountPath: /sys/kernel/debug
            - name: modules
              mountPath: /lib/modules/
            - name: cgroup
              mountPath: /sys/fs/cgroup
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: kernel
          hostPath:
            path: /sys/kernel/debug
            type: Directory
        - name: modules
          hostPath:
            path: /lib/modules/
            type: Directory
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
